#!/bin/bash
lec_num=$1
day_now="$(date +%d)"
month_now="$(date +%m)"
year_now="$(date +%Y)"

cd ~/codebase/book-exercises/cpsc210

echo "NEW LECTURE: Lecture $lec_num ($month_now/$day_now)"

# make lecture files
echo "Create directory -> ./lecture/lec$lec_num"
mkdir ./lecture/lec$lec_num

echo "Copy template.md -> ./notes-lecture/lec$lec_num.md"
cp ./notes-lecture/template.md ./notes-lecture/lec$lec_num.md

echo "Set fields -> ./notes-lecture/lec$lec_num.md"
sed -i "s/LECNUM/$lec_num/g" ./notes-lecture/lec$lec_num.md
sed -i "s/DD/$day_now/g" ./notes-lecture/lec$lec_num.md
sed -i "s/MM/$month_now/g" ./notes-lecture/lec$lec_num.md
sed -i "s/YYYY/$year_now/g" ./notes-lecture/lec$lec_num.md

echo "Launch Visual Studio Code -> ./lec/lec$lec_num.md"
code ./notes-lecture/lec$lec_num.md
