#!/bin/bash
if [ \( "$1" = "-h" \) -o \( "$1" = "--help" \) -o \( "$1" = "" \) -o \( "$2" = "" \) -o \( "$3" = "" \) -o \( "$4" = "" \) ]
then
    echo Usage: nm [MODULE] [LESSON] [FORMAT_NAME] [FILE_NAME]
    echo
    column -t -s "|" nm-help.txt
else
    module=$1
    lesson=$2
    format_name=$3
    file_name_title=$4

    folder="/"
    file_name="u$module-$file_name_title"
    if [ $module = 1 ]; then
        folder="m1-basics"
        file_name="b$lesson-$file_name_title"
    elif [ $module = 2 ]; then
        folder="m2-abstraction"
        file_name="a$lesson-$file_name_title"
    elif [ $module = 3 ]; then
        folder="m3-construction"
        file_name="c$lesson-$file_name_title"
    elif [ $module = 4 ]; then
        folder="m4-design"
        file_name="d$lesson-$file_name_title"
    else
        folder="uncategorized"
        file_name="u$lesson-$file_name_title"
    fi

    day_now="$(date +%d)"
    month_now="$(date +%m)"
    year_now="$(date +%Y)"

    # make first char of each word uppercase
    # title_lower=echo $format_name | tr '[:upper:]' '[:lower:]' # all to lower
    # title=( $title_lower ) # an array?
    # title=${title[@]^} # capitalize each element?
    title=$format_name

    echo "NEW MODULE: Module $module ($month_now/$day_now)"

    cd ~/codebase/book-exercises/cpsc210

    # make module files
    echo "Copy module-template  -> ./module/$folder/$file_name"
    cp -ra ./module/module-template ./module/$folder/$file_name

    echo "Copy template.md -> ./notes-module/$folder/m$module-$file_name.md"
    cp ./notes-module/template.md ./notes-module/$folder/"m$module-$file_name.md"

    note_module_name="Uncategorized"
    note_lesson_number=$lesson
    note_lesson_title=$3
    if [ $module = 1 ]; then
        note_module_name="Basics"
    elif [ $module = 2 ]; then
        note_module_name="Abstraction"
    elif [ $module = 3 ]; then
        note_module_name="Construction"
    elif [ $module = 4 ]; then
        note_module_name="Design"
    fi

    echo "Set fields -> ./notes-module/$folder/m$module-$file_name.md"
    sed -i "s/MODULENAME/$note_module_name/g" ./notes-module/$folder/"m$module-$file_name.md"
    sed -i "s/LESSONNUMBER/$note_lesson_number/g" ./notes-module/$folder/"m$module-$file_name.md"
    sed -i "s/LESSONTITLE/$note_lesson_title/g" ./notes-module/$folder/"m$module-$file_name.md"
    sed -i "s/TITLE/$title/g" ./notes-module/$folder/"m$module-$file_name.md"
    sed -i "s/DD/$day_now/g" ./notes-module/$folder/"m$module-$file_name.md"
    sed -i "s/MM/$month_now/g" ./notes-module/$folder/"m$module-$file_name.md"
    sed -i "s/YYYY/$year_now/g" ./notes-module/$folder/"m$module-$file_name.md"

    echo "Launch Visual Studio Code -> ./notes-module/$folder/m$module-$file_name.md"
    code ./notes-module/$folder/"m$module-$file_name.md"

    echo "Launch Explorer -> ./module/$folder/$file_name/starter"
    cd ./module/$folder/$file_name/starter
    explorer .
fi
