#!/bin/bash
e_number=$1

e_name=$2
title=$e_name

e_name_file=$3
filename="e$e_number-$e_name_file"

year_now="$(date +%Y)"
month_now="$(date +%m)"
day_now="$(date +%d)"

echo "NEW EPISODE: Episode $e_number ($year_now/$month_now/$day_now)"

cd ~/codebase/learn-elixir/

# make directory and file for this episode
echo "Copy directory ./templates/episode-template -> ./episodes/$filename"
cp -ra ./templates/episode-template ./episodes/$filename
touch ./episodes/$filename/lesson-starters/$filename.exs

# make and format note for this episode
echo "Copy ./templates/note-template.md -> ./notes/$filename.md"
cp ./templates/note-template.md ./notes/"$filename.md"

echo "Set fields -> ./notes/$filename.md"
sed -i "s/xx/$e_number/g" ./notes/"$filename.md"
sed -i "s/Title/$title/g" ./notes/"$filename.md"
sed -i "s/YYYY/$year_now/g" ./notes/"$filename.md"
sed -i "s/MM/$month_now/g" ./notes/"$filename.md"
sed -i "s/DD/$day_now/g" ./notes/"$filename.md"

echo "Launch Visual Studio Code -> ./notes/$filename.md"
code ./notes/"$filename.md"

echo "Launch Visual Studio Code -> ./episodes/$filename/lesson-starters/$filename.exs"
code ./episodes/$filename/lesson-starters/"$filename.exs"
