#!/bin/bash
lec_num=$1
month_now="$(date +%m)"
day_now="$(date +%d)"

cd ~/codebase/book-exercises/cpsc110

echo "NEW LECTURE: Lecture $lec_num ($month_now/$day_now)"

# make lecture files
echo "Create directory -> ./lectures/lec$lec_num"
mkdir ./lectures/lec$lec_num

echo "Copy template.md -> ./lec-notes/lec$lec_num.md"
cp ./lec-notes/template.md ./lec-notes/lec$lec_num.md

echo "Set fields -> ./lec-notes/lec$lec_num.md"
sed -i "s/xx/$lec_num/g" ./lec-notes/lec$lec_num.md
sed -i "s/MM/$month_now/g" ./lec-notes/lec$lec_num.md
sed -i "s/DD/$day_now/g" ./lec-notes/lec$lec_num.md

echo "Launch Visual Studio Code -> ./lec/lec$lec_num.md"
code ./lec-notes/lec$lec_num.md
